server:
  port: 8080
security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:8082/oauth/token
      user-authorization-uri: http://localhost:8082/oauth/authorize
    resource:
      jwt:
        key-uri: http://localhost:8082/oauth/token_key
